<?php

    echo $block->getLayout()

               ->createBlock('Magento\Cms\Block\Block')

               ->setBlockId('insta')

               ->toHtml();

?>

<script type="text/javascript">
	require([
    'jquery',
    'owlcarousel'
], function($) {
    $('.insta-imgs').owlCarousel({
        loop: true,
        nav: false,
        margin: 20,
        items:5,
        responsiveClass: true,
        responsive: {
            0: {
                items: 3
            },
            765: {
                items: 4
            },
            1023: {
                items:5
            }
        }
    });
});
</script>